##############################################################################################
#  Copyright Sownak Roy. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
description: "A Helm chart for Hyperledger Fabric chaincode lifecycle operations (approve, commit, invoke)."
name: fabric-chaincode-lifecycle
version: 1.3.1
appVersion: latest
keywords:
  - bevel
  - hlf
  - fabric
  - hyperledger
  - enterprise
  - blockchain
  - deployment
home: https://hyperledger-bevel.readthedocs.io/en/latest/
sources:
  - https://github.com/hyperledger-bevel/bevel
maintainers:
  - name: Hyperledger Bevel maintainers
    email: bevel@lists.lfdecentralizedtrust.org