##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
dependencies:
  - role: "{{playbook_dir}}/../../shared/configuration/roles/setup/vault"
    vars:
      vault:
        os: "{{ install_os }}"
        arch: "{{ install_arch }}"
        bin_directory: "{{ bin_install_dir }}"
