##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# This playbook is a subsequent playbook
##########################################################################################
# DO NOT RUN THIS IF YOU HAVE NOT RUN deploy-network.yaml and deployed the Fabric network
##########################################################################################
# This playbook can only be run after all pods and orderers are available
# Please use the same network.yaml to run this playbook as used for deploy-network.yaml
---
  # This will apply to ansible_provisioners. /etc/ansible/hosts should be configured with this group
- hosts: ansible_provisioners
  gather_facts: no
  no_log: "{{ no_ansible_log | default(false) }}"
  tasks:
    # This role generate channeltx
    - include_role:
        name: "create/channel_artifacts"
      vars:
        build_path: "./build"
        genesis: "{{ item.genesis }}"
        channel_name: "{{ item.channel_name | lower}}"
        profile_name: "{{ item.channel_name }}"
        add_new_org: 'false'
        fetch_certs: "false"
      loop: "{{ network['channels'] }}"
      when: item.channel_status == 'new'

    # This role creates the value file for creating channel from one organization
    # to the vault.
    - include_role:
        name: "create/channels"
      vars:
        build_path: "./build"
        participants: "{{ item.participants }}"
        docker_url: "{{ network.docker.url }}"
      loop: "{{ network['channels'] }}"
      when: item.channel_status == 'new'

    # This role creates the value file for joining channel from each participating peer
    # to the vault.
    - include_role:
        name: "create/channels_join"
      vars:
        build_path: "./build"
        docker_url: "{{ network.docker.url }}"
        participants: "{{ item.participants }}"
      loop: "{{ network['channels'] }}"
      
    # delete build directory
    - name: Remove build directory
      file:
        path: "./build"
        state: absent    
  vars: #These variables can be overriden from the command line
    privilege_escalate: false           #Default to NOT escalate to root privledges
    install_os: "linux"                 #Default to linux OS
    install_arch:  "amd64"              #Default to amd64 architecture
    bin_install_dir:  "~/bin"            #Default to /bin install directory for binaries
