##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
---
# Create value file for chaincode invokes 
- name: "Create value file for chaincode invokes"
  include_tasks: valuefile.yaml
  loop: "{{ peer_chaincodes }}"
  loop_control:
    loop_var: chaincode
  when: 
    - chaincode.external_chaincode is defined and chaincode.external_chaincode == true
    - peer.peerstatus is not defined or peer.peerstatus == 'new'
