dependencies:
  - name: bevel-storageclass
    alias: storage
    repository: "file://../../../shared/charts/bevel-storageclass"
    tags:
      - storage
    version: ~1.3.1
    condition: storage.enabled
  - name: fabric-catools
    alias: certs
    repository: "file://../fabric-catools"
    tags:
      - catools
    version: ~1.3.1
    condition: certs.generateCertificates
  - name: fabric-cli
    alias: peer
    repository: "file://../fabric-cli"
    tags:
      - cli
    version: ~1.3.1
    condition: peer.cliEnabled
