##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

#############################################################################################
# This role generate initial CA certs and push them to vault
# Also, creates the value file for Certificate Authority (CA)
#############################################################################################

# Copy custom config for fabric-ca server
- name: Copy custom config for fabric-ca server
  shell: |
    cp {{ ca.configpath }} ../../../{{ gitops.chart_source }}/ca/conf/fabric-ca-server-config-{{ component }}.yaml
  when: ca.configpath is defined

- name: Get the kubernetes server url
  shell: |
    KUBECONFIG={{ kubernetes.config_file }} kubectl config view --minify | grep server | cut -f 2- -d ":" | tr -d " "
  register: kubernetes_server_url

# Create the CA value file
- name: "Create CA server values"
  include_role:
    name: helm_component
  vars:
    type: "ca-server"
    name: "ca"
    component_name: "{{ ca.name | lower }}"
    git_protocol: "{{ gitops.git_protocol }}"
    git_url: "{{ gitops.git_url }}"
    git_branch: "{{ gitops.branch }}"
    charts_dir: "{{ gitops.chart_source }}"
    subject: "{{ ca.subject | quote }}"
    external_url_suffix: "{{ org.external_url_suffix }}"
    kubernetes_url: "{{ kubernetes_server_url.stdout }}"

# Git Push: Push the above generated files to git directory 
- name: Git Push
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    gitops: "{{ org.gitops }}"
    msg: "[ci skip] Pushing CA Server files"

# Check if CA server is available
- name: "Waiting for the CA server to be created in {{ org.name | lower }}-net"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    component_type: "Pod"
    namespace: "{{ org.name | lower }}-net"
    component_name: "{{ ca.name }}"
    label_selectors:
      - app = {{ component_name }}

- name: Create certificate directory
  file:
    path: "{{ org.ca_data.certificate | dirname }}"
    state: directory
    mode: '0755'
    recurse: yes

# Copy tls server.crt from vault to the build directory
- name: Fetch the tls server.crt from vault
  shell: |
    vault kv get -field=rootca_pem {{ vault.secret_path | default('secretsv2') }}/{{ network.env.type }}{{ org.name | lower }}/ca > {{ org.ca_data.certificate }}
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
